version: '3.8'

services:
  sqlserver:
    build:
      context: .
      dockerfile: sqlserver.Dockerfile
    container_name: sqlserver_embalagens
    environment:
      SA_PASSWORD: "Embalagens123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./Embalagens/Script:/scripts
      - ./init.sh:/scripts/init.sh
    networks:
      - embalagens-network
    command: ["/bin/bash", "/scripts/init.sh"]

  embalagensapi:
    build:
      context: .
      dockerfile: ./Embalagens/Dockerfile
    container_name: embalagens_api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EmbalagensDb;User Id=sa;Password=Embalagens123!;TrustServerCertificate=True;
    ports:
      - "5000:80"
    networks:
      - embalagens-network

volumes:
  sqlserverdata:

networks:
  embalagens-network:
    driver: bridge